# Order from Chaos

In [1]:
# from bokeh.plotting import figure, output_file, show
import gzip
import io
import pandas as pd
import urllib.request

%matplotlib inline

import matplotlib # plotting
import matplotlib.pyplot as plt

import sqlite3

%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

## Three Worlds in One

### Normal Python

In [2]:
# unmodified python
x = 'HELLO'
x.lower()

'hello'

In [3]:
# print first two letters
x[0:2]

'HE'

### Pandas

In [4]:
# pandas is very good at handling rows and columns
ramphs = pd.read_csv("http://sebastianheath.com/roman-amphitheaters/roman-amphitheaters.csv")
chronogrps = pd.read_csv("http://sebastianheath.com/roman-amphitheaters/chronogrps.csv")

In [7]:
# print the first two rows of ramphs
ramphs.province # this is just like string indexing

0                    syria
1              narbonensis
2              lugdunensis
3                      NaN
4                      NaN
5                      NaN
6                   judaea
7                      NaN
8                lusitania
9                britannia
10               lusitania
11                     NaN
12                     NaN
13                     NaN
14                 sicilia
15           proconsularis
16                     NaN
17                  achaea
18                 thracia
19                   dacia
20       germania-superior
21                pannonia
22                pannonia
23                pannonia
24           proconsularis
25           tarraconensis
26           tarraconensis
27     corsica-et-sardinia
28                 baetica
29           tarraconensis
              ...
230          proconsularis
231          proconsularis
232                    NaN
233                    NaN
234                    NaN
235                    NaN
236                    NaN
237                    NaN
238                    NaN
239                    NaN
240                    NaN
241          proconsularis
242          proconsularis
243    corsica-et-sardinia
244                    NaN
245                    NaN
246                    NaN
247                    NaN
248                    NaN
249                    NaN
250                 judaea
251                    NaN
252                    NaN
253                    NaN
254              britannia
255          tarraconensis
256                thracia
257              britannia
258                    NaN
259    corsica-et-sardinia
Name: province, Length: 260, dtype: object

In [8]:
# print the first two rows as lower case
ramphs.modcountry.str.lower()[0:2]

0     syria
1    france
Name: modcountry, dtype: object

In [9]:
# but note we haven't changed the column itself
ramphs.modcountry[0:2]

0     Syria
1    France
Name: modcountry, dtype: object

### sqlite

In [10]:
# Now into sqlite
# create the database
ramphs_sql = sqlite3.connect(":memory:")

# ramphs_sql is a python variable that gives access to the sqlite database

In [11]:
# add ramphs and chronogrps tables to the sqlite database
ramphs.to_sql('ramphs',ramphs_sql,if_exists = "replace")
chronogrps.to_sql('chronogrps',ramphs_sql,if_exists = "replace")

In [12]:
# Non pandas way of accessing tables in the database
# create cur as a variable with methods that let us send queries to the sqlite database
cur = ramphs_sql.cursor()

# cur has an .execute method
cur.execute("SELECT id,modcountry FROM ramphs WHERE modcountry = 'France'")
for i in cur.fetchall():
    print(i)

# it is good practice to close a cursor when you're done with it
cur.close()
# the output is not very nicely formatted

('arlesAmphitheater', 'France')
('lyonAmphitheater', 'France')
('parisAmphitheater', 'France')
('nimesAmphitheater', 'France')
('gennesAmphitheater', 'France')
('bordeauxAmphitheater', 'France')
('cimiezAmphitheater', 'France')
('perigueuxAmphitheater', 'France')
('saintesAmphitheater', 'France')
('frejusAmphitheater', 'France')
('toulouseAmphitheater', 'France')
('lillebonnAmphitheater', 'France')
('besanconAmphitheater', 'France')
('limogesAmphitheater', 'France')
('poitiersAmphitheater', 'France')
('reimsAmphitheater', 'France')
('rodezAmphitheater', 'France')
('beziersAmphitheater', 'France')
('agenAmphitheater', 'France')
('narbonneAmphitheater', 'France')
('amiensAmphitheater', 'France')
('meauxAmphitheater', 'France')
('chartresAmphitheater', 'France')
('senlisAmphitheater', 'France')
('toursAmphitheater', 'France')
('autunAmphitheater', 'France')
('stMarcelAmphitheater', 'France')
('metzAmphitheater', 'France')
('grandHalfAmphitheater', 'France')
('bourgesAmphitheater', 'France')
('chassenonAmphitheater', 'France')
('drevantAmphitheater', 'France')
('montbouyGalloRomanAmphitheater', 'France')
('aquaeNeriAmphitheater', 'France')
('aleriaAmphitheater', 'France')

In [13]:
# it's simpler with pandas
pd.read_sql_query("SELECT id,modcountry FROM ramphs WHERE modcountry = 'France'", ramphs_sql)
# a single line produces useful result

                                id modcountry
0                arlesAmphitheater     France
1                 lyonAmphitheater     France
2                parisAmphitheater     France
3                nimesAmphitheater     France
4               gennesAmphitheater     France
5             bordeauxAmphitheater     France
6               cimiezAmphitheater     France
7            perigueuxAmphitheater     France
8              saintesAmphitheater     France
9               frejusAmphitheater     France
10            toulouseAmphitheater     France
11           lillebonnAmphitheater     France
12            besanconAmphitheater     France
13             limogesAmphitheater     France
14            poitiersAmphitheater     France
15               reimsAmphitheater     France
16               rodezAmphitheater     France
17             beziersAmphitheater     France
18                agenAmphitheater     France
19            narbonneAmphitheater     France
20              amiensAmphitheater     France
21               meauxAmphitheater     France
22            chartresAmphitheater     France
23              senlisAmphitheater     France
24               toursAmphitheater     France
25               autunAmphitheater     France
26            stMarcelAmphitheater     France
27                metzAmphitheater     France
28           grandHalfAmphitheater     France
29             bourgesAmphitheater     France
30           chassenonAmphitheater     France
31             drevantAmphitheater     France
32  montbouyGalloRomanAmphitheater     France
33           aquaeNeriAmphitheater     France
34              aleriaAmphitheater     France

## Joining Tables

In [15]:
# edit this to list the numeric start date of every amphitheater. 
# once you get basic query add an ORDER BY statement to sort by that date.
# note that I've '?'s in the WHERE clause. That's what you need to change.
# we did this in class so I think this will seem familiar
df = pd.read_sql_query('''SELECT ramphs.id, chronogrps.start
    FROM ramphs, chronogrps
    WHERE ramphs.chronogrp = chronogrps.chronogrp
    ORDER BY chronogrps.start
    ''',ramphs_sql)
df

                                  id  start
0                pompeiiAmphitheater    -70
1                  cumaeAmphitheater    -70
2          pozzuoliEarlyAmphitheater    -70
3                paestumAmphitheater    -70
4                 avellaAmphitheater    -70
5                ferentoAmphitheater    -70
6                sutriumAmphitheater    -70
7                telesiaAmphitheater    -70
8                antiochAmphitheater    -70
9              beneventoAmphitheater    -70
10          calviRisortaAmphitheater    -70
11       capuaRepublicanAmphitheater    -70
12               liternoAmphitheater    -70
13                  noleAmphitheater    -70
14                 teanoAmphitheater    -70
15          suessaAruncaAmphitheater    -70
16            altripaldaAmphitheater    -70
17                compsaAmphitheater    -70
18               corinthAmphitheater    -49
19               carmonaAmphitheater    -49
20                espejoAmphitheater    -49
21                meridaAmphitheater    -27
22            conimbrigaAmphitheater    -27
23              syracuseAmphitheater    -27
24               roselleAmphitheater    -27
25                luceraAmphitheater    -27
26                cimiezAmphitheater    -27
27                veronaAmphitheater    -27
28            albaFucensAmphitheater    -27
29             cherchellAmphitheater    -27
..                               ...    ...
230              chemtouAmphitheater    100
231       genzanoPrivateAmphitheater    100
232            ainHedjahAmphitheater    100
233                uticaAmphitheater    100
234             tebourbaAmphitheater    100
235      hencherElKasbatAmphitheater    100
236        hencherZembraAmphitheater    100
237               botriaAmphitheater    100
238              portusOvalStructure    100
239          mesarafeltaAmphitheater    100
240         tigavaCastraAmphitheater    100
241             tusculumAmphitheater    100
242  aureliumCommodianumAmphitheater    100
243         hadrianVillaAmphitheater    117
244             gemellaeAmphitheater    117
245                toursAmphitheater    117
246               riminiAmphitheater    117
247                augstAmphitheater    150
248               tipasaAmphitheater    150
249           bullaRegiaAmphitheater    150
250          duraEuroposAmphitheater    193
251       romeAmphitheatrumCastrense    193
252        marcianopolisAmphitheater    193
253              bararusAmphitheater    193
254         castraAlbanaAmphitheater    193
255            grandHalfAmphitheater    200
256              egnaziaAmphitheater    200
257             thysdrusAmphitheater    235
258               sophiaAmphitheater    235
259          aphrodisiasAmphitheater    300

[260 rows x 2 columns]

In [19]:
# we ran this query in class
# edit it so it does different things
df = pd.read_sql_query('''SELECT ramphs.id, ramphs.modcountry, chronogrps.start, ramphs.province
    FROM ramphs, chronogrps
    WHERE ramphs.chronogrp = chronogrps.chronogrp and ramphs.modcountry = "France"
       AND chronogrps.start > 50
    ORDER BY ramphs.province
    ''',ramphs_sql)
df

                       id modcountry  start           province
0    bordeauxAmphitheater     France    100          aquitania
1     limogesAmphitheater     France    100          aquitania
2      amiensAmphitheater     France    100            belgica
3        metzAmphitheater     France     75            belgica
4   grandHalfAmphitheater     France    200            belgica
5    besanconAmphitheater     France    100  germania-superior
6        lyonAmphitheater     France    100        lugdunensis
7       parisAmphitheater     France     69        lugdunensis
8      gennesAmphitheater     France    100        lugdunensis
9       toursAmphitheater     France    117        lugdunensis
10      arlesAmphitheater     France     69        narbonensis
11      nimesAmphitheater     France     69        narbonensis
12     frejusAmphitheater     France     69        narbonensis
13   narbonneAmphitheater     France     69        narbonensis

## Adding Pleiades so we have a lot of data to work with

In [41]:
# get pleiades data
# this transfer takes a while so only execute this cell as necessary
response = urllib.request.urlopen("http://atlantides.org/downloads/pleiades/dumps/pleiades-places-latest.csv.gz")
pleiades = pd.read_csv(io.BytesIO(gzip.decompress(response.read())))

In [42]:
list(pleiades)

['authors',
 'bbox',
 'connectsWith',
 'created',
 'creators',
 'currentVersion',
 'description',
 'extent',
 'featureTypes',
 'geoContext',
 'hasConnectionsWith',
 'id',
 'locationPrecision',
 'maxDate',
 'minDate',
 'modified',
 'path',
 'reprLat',
 'reprLatLong',
 'reprLong',
 'tags',
 'timePeriods',
 'timePeriodsKeys',
 'timePeriodsRange',
 'title',
 'uid']

In [43]:
# you can always repeat this cell to reload the pleiades table
pleiades.to_sql('pleiades',ramphs_sql,if_exists = "replace")

In [58]:
# this was where things got whacky in class
cur = ramphs_sql.cursor()
# let's use direct access to the sqlite database to update the pleiades sqlite table
cur.execute("UPDATE pleiades SET path = 'https://pleiades.stoa.org'||path")
cur.close()

# what did we just do? Briefly...
# The '||' combines two string together. The UPDATE command of SQL can change values in all rows of a column

In [59]:
# test that it worked
pd.read_sql_query("SELECT path FROM pleiades LIMIT 5", ramphs_sql)

                                        path
0  https://pleiades.stoa.org/places/48210385
1  https://pleiades.stoa.org/places/48210386
2    https://pleiades.stoa.org/places/265876
3    https://pleiades.stoa.org/places/265877
4    https://pleiades.stoa.org/places/265878

In [60]:
# find amphitheaters in "Pleiades Roman only" sites
# now ramphs.pleiades shares values with pleiades.path
# we ran this query in class

pd.read_sql_query('''SELECT  ramphs.id, pleiades.timePeriods, ramphs.province
          FROM ramphs, pleiades
          WHERE ramphs.pleiades = pleiades.path and pleiades.timePeriods = 'R'
          ORDER BY ramphs.province;''', ramphs_sql)
# this is where we ended in class

                           id timePeriods           province
0               zagaroloLudus           R               None
1            metzAmphitheater           R            belgica
2     tomen-y-murAmphitheater           R          britannia
3        newsteadAmphitheater           R          britannia
4           miciaAmphitheater           R              dacia
5      porolissumAmphitheater           R              dacia
6   sarmizegetusaAmphitheater           R              dacia
7        arnsburgAmphitheater           R  germania-superior
8        bobadelaAmphitheater           R          lusitania
9    tigavaCastraAmphitheater           R         mauretania
10        dambachAmphitheater           R             raetia

In [47]:
# your intermediate task: edit the following sql so that the chronogrps.start
# column is added to the output.
# That will mean your pulling data from three tables

# HINT: you need to make a change to the SELECT clause, to the FROM clause, and to the WHERE clauses
# but it's the WHERE clause that does the work. Remember, I stressed you can
# add multiple "AND"s. 
pd.read_sql_query('''SELECT  ramphs.id, pleiades.timePeriods, chronogrps.start
          FROM ramphs, pleiades, chronogrps
          WHERE ramphs.pleiades = pleiades.path AND ramphs.chronogrp = chronogrps.chronogrp 
          ORDER By chronogrps.start;''', ramphs_sql)


# MORE HINTS BUT DON"T READ THESE UNTIL YOU'VE TRIED TO DO TASK ON YOUR OWN
# What is the column you need to add to the SELECT clause?
# What is the table you need to add to the FROM clause?
# You need a new " AND ..." 'subclause' of the WHERE clause. One that joins ramphs and chronogrps. We've done this already

                                  id                  timePeriods  start
0                pompeiiAmphitheater                       ACHHRM    -70
1                  cumaeAmphitheater                        ACHRL    -70
2          pozzuoliEarlyAmphitheater                      ACHRRLM    -70
3                paestumAmphitheater                      ACHRLMM    -70
4                 avellaAmphitheater                          HRL    -70
5                ferentoAmphitheater                         CHRL    -70
6                sutriumAmphitheater                         CHRL    -70
7                telesiaAmphitheater                          HRL    -70
8                antiochAmphitheater  M1AHHRRRTLLPCEASMRCCIOE1LMM    -70
9              beneventoAmphitheater                        HRLMM    -70
10          calviRisortaAmphitheater                         CHRL    -70
11       capuaRepublicanAmphitheater                        ACHRL    -70
12               liternoAmphitheater                         HHRR    -70
13                  noleAmphitheater                        ACHRL    -70
14                 teanoAmphitheater                       ACHRLM    -70
15          suessaAruncaAmphitheater                        ACHRL    -70
16            altripaldaAmphitheater                          HRL    -70
17                compsaAmphitheater                         CRRL    -70
18               corinthAmphitheater                        ACHRM    -49
19               carmonaAmphitheater                      ACHRLMM    -49
20                espejoAmphitheater                           HR    -49
21                meridaAmphitheater                          RLM    -27
22            conimbrigaAmphitheater                        ACHRL    -27
23              syracuseAmphitheater                      ACHHRLM    -27
24               roselleAmphitheater                       ACHRLM    -27
25                luceraAmphitheater                       CHRLMM    -27
26                cimiezAmphitheater                         HRLM    -27
27                veronaAmphitheater                           RL    -27
28            albaFucensAmphitheater                         HRLM    -27
29             cherchellAmphitheater                       CHRRLM    -27
..                               ...                          ...    ...
230              chemtouAmphitheater                        HRRLM    100
231       genzanoPrivateAmphitheater                           RL    100
232            ainHedjahAmphitheater                           RL    100
233                uticaAmphitheater                       ACHHRL    100
234             tebourbaAmphitheater                         HRLM    100
235      hencherElKasbatAmphitheater                          HRL    100
236        hencherZembraAmphitheater                          HRL    100
237               botriaAmphitheater                          HRL    100
238              portusOvalStructure                          RLM    100
239          mesarafeltaAmphitheater                           RL    100
240         tigavaCastraAmphitheater                            R    100
241             tusculumAmphitheater                       ACHRLM    100
242  aureliumCommodianumAmphitheater                           RL    100
243         hadrianVillaAmphitheater                          HRL    117
244             gemellaeAmphitheater                           RL    117
245                toursAmphitheater                          RLM    117
246               riminiAmphitheater                         CHRL    117
247                augstAmphitheater                         HRLM    150
248               tipasaAmphitheater                        CHRRL    150
249           bullaRegiaAmphitheater                         HRRL    150
250          duraEuroposAmphitheater                          HRL    193
251       romeAmphitheatrumCastrense                       ACHRLM    193
252        marcianopolisAmphitheater                           RL    193
253              bararusAmphitheater                           RL    193
254         castraAlbanaAmphitheater                          RRL    193
255            grandHalfAmphitheater                          RLM    200
256              egnaziaAmphitheater                        ACHRL    200
257             thysdrusAmphitheater                        HRRLM    235
258               sophiaAmphitheater                          RLM    235
259          aphrodisiasAmphitheater                         CHRL    300

[260 rows x 3 columns]

In [ ]:
# YOUR ASSIGNMENT is either
# 1) Adapt the above SELECT query to do something like:
# "Find all amphitheaters in Italy from sites that Pleiades thinks were founded before 323 BC. Order by earliest date of the amphitheater." 
# Hint: Use the pleiades.minDate column
# Then make some variations on that theme
# OR
# 2) load your own data and write SELECT queries that join tables on common values.

# Add this edited iPyton notebook to your github repository and put a link to it in the Google Doc

In [48]:
pd.read_sql_query('''SELECT  ramphs.id, pleiades.timePeriods, chronogrps.end
          FROM ramphs, pleiades, chronogrps
          WHERE ramphs.pleiades = pleiades.path AND ramphs.chronogrp = chronogrps.chronogrp 
          ORDER By chronogrps.end;''', ramphs_sql)

                              id                  timePeriods  end
0            corinthAmphitheater                        ACHRM  -44
1            carmonaAmphitheater                      ACHRLMM  -44
2             espejoAmphitheater                           HR  -44
3            pompeiiAmphitheater                       ACHHRM  -31
4              cumaeAmphitheater                        ACHRL  -31
5      pozzuoliEarlyAmphitheater                      ACHRRLM  -31
6            paestumAmphitheater                      ACHRLMM  -31
7             avellaAmphitheater                          HRL  -31
8            ferentoAmphitheater                         CHRL  -31
9            sutriumAmphitheater                         CHRL  -31
10           telesiaAmphitheater                          HRL  -31
11           antiochAmphitheater  M1AHHRRRTLLPCEASMRCCIOE1LMM  -31
12         beneventoAmphitheater                        HRLMM  -31
13      calviRisortaAmphitheater                         CHRL  -31
14   capuaRepublicanAmphitheater                        ACHRL  -31
15           liternoAmphitheater                         HHRR  -31
16              noleAmphitheater                        ACHRL  -31
17             teanoAmphitheater                       ACHRLM  -31
18      suessaAruncaAmphitheater                        ACHRL  -31
19        altripaldaAmphitheater                          HRL  -31
20            compsaAmphitheater                         CRRL  -31
21            luceraAmphitheater                       CHRLMM   14
22         cherchellAmphitheater                       CHRRLM   14
23   statiliusTaurusAmphitheater                       ACHRLM   14
24       faleriiNoviAmphitheater                          HRL   14
25            meridaAmphitheater                          RLM   68
26        conimbrigaAmphitheater                        ACHRL   68
27          syracuseAmphitheater                      ACHHRLM   68
28       leptisMagnaAmphitheater                        ACHRL   68
29           roselleAmphitheater                       ACHRLM   68
..                           ...                          ...  ...
230           bevanaAmphitheater                          HRL  280
231         sinuessaAmphitheater                          HRM  280
232           djerbaAmphitheater                          HRL  280
233                zagaroloLudus                            R  280
234             todiAmphitheater                       ACHRLM  280
235          spoletoAmphitheater                        HRRLM  280
236      jebelMorabaAmphitheater                            H  280
237            fermoAmphitheater                       ACHRLM  280
238        frosinoneAmphitheater                         HRLM  280
239            ruggeAmphitheater                         ACHR  280
240           canosaAmphitheater                       ACHRRL  280
241          sipontoAmphitheater                          HRM  280
242           chietiAmphitheater                        CHRLM  280
243     henchirDuomaAmphitheater                          HRL  280
244        ainToungaAmphitheater                         HRLM  280
245           aleriaAmphitheater                        ACHRL  280
246            vastoAmphitheater                         CHRL  280
247            suasaAmphitheater                          HRL  280
248         pollenzoAmphitheater                          RRL  280
249         vercelliAmphitheater                        CHRLM  280
250      sanGiovanniAmphitheater                           HR  280
251          megiddoAmphitheater                           RL  280
252             yorkAmphitheater                           RL  280
253        barcelonaAmphitheater                          RLM  280
254         istanbulAmphitheater                        ACHRL  280
255     reggioEmiliaAmphitheater                          RLM  280
256          tharrosAmphitheater                        ACHRL  280
257        grandHalfAmphitheater                          RLM  299
258          egnaziaAmphitheater                        ACHRL  299
259      aphrodisiasAmphitheater                         CHRL  350

[260 rows x 3 columns]

In [61]:
pd.read_sql_query('''SELECT  ramphs.id, ramphs.modcountry, pleiades.minDate, pleiades.timePeriods, chronogrps.start
          FROM ramphs, pleiades, chronogrps
          WHERE ramphs.pleiades = pleiades.path AND ramphs.chronogrp = chronogrps.chronogrp AND ramphs.modcountry = "Italy" AND pleiades.mindate < 323
          ORDER By chronogrps.start;''', ramphs_sql)

                                 id modcountry  minDate timePeriods  start
0               pompeiiAmphitheater      Italy   -750.0      ACHHRM    -70
1                 cumaeAmphitheater      Italy   -750.0       ACHRL    -70
2         pozzuoliEarlyAmphitheater      Italy   -750.0     ACHRRLM    -70
3               paestumAmphitheater      Italy   -750.0     ACHRLMM    -70
4                avellaAmphitheater      Italy   -330.0         HRL    -70
5               ferentoAmphitheater      Italy   -550.0        CHRL    -70
6               sutriumAmphitheater      Italy   -550.0        CHRL    -70
7               telesiaAmphitheater      Italy   -330.0         HRL    -70
8             beneventoAmphitheater      Italy   -330.0       HRLMM    -70
9          calviRisortaAmphitheater      Italy   -550.0        CHRL    -70
10      capuaRepublicanAmphitheater      Italy   -750.0       ACHRL    -70
11              liternoAmphitheater      Italy   -330.0        HHRR    -70
12                 noleAmphitheater      Italy   -750.0       ACHRL    -70
13                teanoAmphitheater      Italy   -750.0      ACHRLM    -70
14         suessaAruncaAmphitheater      Italy   -750.0       ACHRL    -70
15           altripaldaAmphitheater      Italy   -330.0         HRL    -70
16               compsaAmphitheater      Italy   -550.0        CRRL    -70
17             syracuseAmphitheater      Italy   -750.0     ACHHRLM    -27
18              roselleAmphitheater      Italy   -750.0      ACHRLM    -27
19               luceraAmphitheater      Italy   -550.0      CHRLMM    -27
20               veronaAmphitheater      Italy    -30.0          RL    -27
21           albaFucensAmphitheater      Italy   -330.0        HRLM    -27
22                paduaAmphitheater      Italy   -750.0     ACHRRLM    -27
23               anconaAmphitheater      Italy   -550.0        CHRL    -27
24      statiliusTaurusAmphitheater      Italy   -750.0      ACHRLM    -27
25   augustaBagiennorumAmphitheater      Italy   -330.0         HRL    -27
26                aostaAmphitheater      Italy    -30.0         RLM    -27
27          faleriiNoviAmphitheater      Italy   -330.0         HRL    -27
28              velleiaAmphitheater      Italy   -330.0        HRRL    -27
29             faleroneAmphitheater      Italy   -330.0         HRL    -27
..                              ...        ...      ...         ...    ...
73              spoletoAmphitheater      Italy   -330.0       HRRLM     50
74                fermoAmphitheater      Italy   -750.0      ACHRLM     50
75            frosinoneAmphitheater      Italy   -330.0        HRLM     50
76                ruggeAmphitheater      Italy   -750.0        ACHR     50
77               canosaAmphitheater      Italy   -750.0      ACHRRL     50
78              sipontoAmphitheater      Italy   -330.0         HRM     50
79               chietiAmphitheater      Italy   -550.0       CHRLM     50
80                vastoAmphitheater      Italy   -550.0        CHRL     50
81                suasaAmphitheater      Italy   -330.0         HRL     50
82             pollenzoAmphitheater      Italy    -30.0         RRL     50
83             vercelliAmphitheater      Italy   -550.0       CHRLM     50
84          sanGiovanniAmphitheater      Italy   -330.0          HR     50
85         reggioEmiliaAmphitheater      Italy    -30.0         RLM     50
86              tharrosAmphitheater      Italy   -750.0       ACHRL     50
87          romeFlavianAmphitheater      Italy   -750.0      ACHRLM     69
88      pozzuoliFlavianAmphitheater      Italy   -750.0     ACHRRLM     69
89               arezzoAmphitheater      Italy   -750.0      ACHRLM     69
90           urbisagliaAmphitheater      Italy   -330.0         HRL     69
91       terminiImereseAmphitheater      Italy   -550.0      CHHRLM     69
92              bolsenaAmphitheater      Italy   -330.0         HRL     69
93        capuaImperialAmphitheater      Italy   -750.0       ACHRL     69
94             cagliariAmphitheater      Italy   -750.0      ACHRLM    100
95       genzanoPrivateAmphitheater      Italy    -30.0          RL    100
96              portusOvalStructure      Italy    -30.0         RLM    100
97             tusculumAmphitheater      Italy   -750.0      ACHRLM    100
98         hadrianVillaAmphitheater      Italy   -330.0         HRL    117
99               riminiAmphitheater      Italy   -550.0        CHRL    117
100      romeAmphitheatrumCastrense      Italy   -750.0      ACHRLM    193
101        castraAlbanaAmphitheater      Italy    -30.0         RRL    193
102             egnaziaAmphitheater      Italy   -750.0       ACHRL    200

[103 rows x 5 columns]